#!/bin/bash

SRC_DIR=./api-spec/protobuf
DST_DIR=./api-spec/protobuf/gen/go
PACKAGE=esplora

mkdir -p $DST_DIR/$PACKAGE
protoc -I=$SRC_DIR \
  --go_out=$DST_DIR/$PACKAGE --go_opt=paths=source_relative \
  --go-grpc_out=$DST_DIR/$PACKAGE --go-grpc_opt=paths=source_relative \
  --grpc-gateway_out $DST_DIR/$PACKAGE \
  --grpc-gateway_opt logtostderr=true \
  --grpc-gateway_opt paths=source_relative \
  --grpc-gateway_opt generate_unbound_methods=true \
  $SRC_DIR/$PACKAGE.proto
